[package]
name = "pig_generic_range"
version = "0.1.0"
edition = "2021"

[dependencies]
my_library = { package="my_library_generic_range", path = "../my_library" }
bevy = {  workspace = true }
bevy_egui = {  workspace = true }
