[package]
name = "bouncy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {  workspace = true }
my_library_flappy_collision = { path = "../my_library" }
anyhow = {  workspace = true }