[package]
name = "pig_generic_mut_random_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
my_library = { package="my_library_mut_random_plugin", path = "../my_library" }
bevy = {  workspace = true }
bevy_egui = {  workspace = true }
